# Site settings
title: Lucas da Silva - Software Developer
email: agtlucas@me.com
description: >
  A Software Developer who lives in Berlin
baseurl: ""
url: "https://lcs.sh"
twitter_username: _agtlucas
github_username:  AgtLucas
disqus_username: lucasninja

exclude: ['node_modules', 'package.json', 'gulpfile.js', 'src', '.DS_Store', '.sass-cache', 'README.md', 'npm-debug.log', 'LICENSE', 'deploy.js', 'Gemfile', 'Gemfile.lock']

# Build settings
kramdown:
  input: GFM

permalink: pretty

compress_html:
  clippings: all
