# Site settings
title: Lucas da Silva - Technical Writer
email: agtlucas@me.com
description: >
  A Technical Writer who lives in Brazil
baseurl: ""
url: "https://agtlucas.com"
twitter_username: _agtlucas
github_username: AgtLucas

exclude:
  [
    "node_modules",
    "package.json",
    "gulpfile.js",
    "src",
    ".DS_Store",
    ".sass-cache",
    "README.md",
    "npm-debug.log",
    "LICENSE",
    "deploy.js",
    "Gemfile",
    "Gemfile.lock",
  ]

include: ["_redirects"]

# Build settings
kramdown:
  input: GFM

permalink: pretty

compress_html:
  clippings: all
