# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lucas
email: lucas@lucas.ninja
description: > # this means to ignore newlines until "baseurl:"
  Front-End Developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lucas.ninja" # the base hostname & protocol for your site
twitter_username: _agtlucas
github_username:  AgtLucas
disqus_username: lucasninja

exclude: ['node_modules', 'package.json', 'gulpfile.js', 'src', '.DS_Store', '.sass-cache', 'README.md', 'npm-debug.log', 'LICENSE', 'deploy.js']

# Build settings
kramdown:
  input: GFM

compress_html:
  clippings: all
