# Site settings
title: Lucas da Silva, Front-End Developer
email: lucas@lucas.ninja
description: >
  Front-End Developer
baseurl: ""
url: "https://lucas.ninja"
twitter_username: _agtlucas
github_username:  AgtLucas
disqus_username: lucasninja

exclude: ['node_modules', 'package.json', 'gulpfile.js', 'src', '.DS_Store', '.sass-cache', 'README.md', 'npm-debug.log', 'LICENSE', 'deploy.js']

# Build settings
kramdown:
  input: GFM

permalink: pretty

compress_html:
  clippings: all
